[build]
  command = "./build.sh"
  functions = "functions"
  publish = "static"

[build.environment]
  GO_IMPORT_PATH = "github.com/serverless-coding/chatgpt"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://github.com/:splat"
  status = 200